Add integration with Travis CI
kpi-web-guild/django-girls-blog-RootenberG pull request #12
Opened 2019-06-01 12:47 UTC by RootenberG

2019-06-01 17:38 UTC, webknjaz commented
@RootenberG you need to use `Closes #xxx` to refer to the relevant issue

2019-06-01 18:05 UTC, RootenberG commented
> @RootenberG you need to use `Closes #xxx` to refer to the relevant issue

Of course, my bad.

2019-06-01 18:38 UTC, webknjaz requested changes
The first commit looks ok

2019-06-01 18:38 UTC, webknjaz commented on .travis.yml
> +    include:
Plz use double space indentation for mappings
```suggestion
  include:
```

2019-06-01 18:38 UTC, webknjaz commented on .travis.yml
> +        - python: 3.6
And zero indentation for sequence items
```suggestion
    - python: 3.6
```

2019-06-01 18:38 UTC, webknjaz commented on .travis.yml
> +          sudo: true
`sudo` option is long deprecated. It used to control whether Travis will spawn full VMs or docker containers for jobs. But now it only supports VMs.

2019-06-01 18:38 UTC, webknjaz commented on .travis.yml
> +matrix:
You don't really need a matrix. The task was to have just Python 3.7 there.
But if you want both, there's matrix expansion for certain options like:
```suggestion
python:
- "3.7"
- "3.6"
```

2019-06-01 18:45 UTC, DrEdi requested changes

2019-06-01 18:45 UTC, DrEdi commented on .travis.yml
> +script: pre-commit run --all-files
No new line at the end of file :)

2019-06-23 13:17 UTC, webknjaz submitted a review, later dismissed
I prefer history to be cleaner. But other than that it's ok.

2019-06-26 14:14 UTC, webknjaz commented
Rebase this after merging #15

2019-07-12 21:00 UTC, webknjaz commented
Rebase this

2019-07-15 19:58 UTC, RootenberG commented
> Rebase this

Done

2019-07-15 20:25 UTC, webknjaz commented
> Done

Not done.

2019-07-23 21:57 UTC, webknjaz approved these changes

2019-07-23 22:16 UTC, merged