Create Blog app and config for it
kpi-web-guild/django-girls-blog-RootenberG pull request #24
Opened 2019-08-23 21:15 UTC by RootenberG

2019-08-24 07:06 UTC, webknjaz commented on blog/__init__.py
> +"""Django website."""
```suggestion
"""Blog web app."""
```

2019-08-24 07:06 UTC, webknjaz commented on blog/admin.py
> +"""Django admin coonfig for mysite."""
mysite?

2019-08-24 07:06 UTC, webknjaz commented on blog/apps.py
> +"""Registry of installed apps for mysite."""
mysite?

2019-08-24 07:08 UTC, webknjaz commented on blog/models.py
> +"""Mysite models."""
mysite? blog db models?

2019-08-24 07:15 UTC, webknjaz commented on blog/models.py
> +        """Return post wich converted to string."""
1) "w***h***ich" is misspelled. the verb is missing, mind your grammar.
2) Plz read the whole data model doc page but especially [this paragraph](https://docs.python.org/3/reference/datamodel.html#object.__str__)
3) You should describe the effect of having this method here which is just support for rendering `Post` instances into strings (by passing it to the `str()` function, usually), it's a part of the Python's string conversion protocol.

So you should just say that this returns a string representation of a Post object. Or, as I usually say, it renders Post as a string.

2019-08-24 07:15 UTC, webknjaz commented on blog/tests.py
> +"""Tests for mysite."""
blog

2019-08-24 07:16 UTC, webknjaz commented on blog/views.py
> +"""Wiews for Blog app."""
```suggestion
"""Views for Blog app."""
```

2019-08-25 20:45 UTC, webknjaz commented
"and" in the PR and commit message suggests that there's two separate changes meaning that they should go to separate atomic commits.

2019-08-25 20:47 UTC, webknjaz requested changes
Blocked on a non-atomic commit.

2019-08-25 21:13 UTC, webknjaz commented
> Add migrations module

it's a package, not a module. + the first commit message still refers to multiple things

2019-08-25 21:18 UTC, RootenberG commented
> > Add migrations module
> 
> it's a package, not a module. + the first commit message still refers to multiple things

Вo you mean a model creating?

2019-08-25 21:19 UTC, webknjaz commented
I mean the commit message.

2019-08-25 21:20 UTC, RootenberG commented
> I mean the commit message.


What changes should I share?

2019-08-25 21:21 UTC, webknjaz commented
You shouldn't say that you exclude a module because you exclude a collection of modules which is a package.

2019-08-25 21:24 UTC, RootenberG commented
I fixed it. What about the first commit?

2019-08-26 06:32 UTC, webknjaz approved these changes
Perfect!

2019-08-26 10:56 UTC, merged